platform: Qradar
source: windows_security


log_source:
  devicetype: [12]

default_log_source:
  devicetype: 12

field_mapping:
  EventID: Event ID
  ParentImage: Parent Process Path
  AccessMask: AccessMask
  AccountName: Account Name
  AllowedToDelegateTo: AllowedToDelegateTo
  AttributeLDAPDisplayName: AttributeLDAPDisplayName
  AuditPolicyChanges: AuditPolicyChanges
  AuthenticationPackageName: AuthenticationPackageName
  CallingProcessName: CallingProcessName
  Channel: Channel
  ComputerName: 
    - Machine Identifier
    - Hostname
  EventType: EventType
  FailureReason: FailureReason
  FileName: Filename
  GrantedAccess: GrantedAccess
  Hashes: File Hash
  HiveName: HiveName
  IpAddress: 
    - sourceip
    - identityIP
  IpPort: sourceport
  KeyLength: KeyLength
  LogonProcessName: LogonProcessName
  LogonType: 
    - Logon Type
    - Login Type
    - MSLogonType
  LinkName: LinkName
  MemberName: MemberName
  MemberSid: MemberSid
  NewProcessName: 
    - Process Name
    - New Process Name
  ObjectClass: ObjectClass
  ObjectName: 
    - Object Name
    - objectname
    - MSFileObjectName
    - ObjectName_Filename
    - ObjectName
  ObjectType: 
    - Object Type
    - ObjectType
  ObjectValueName: ObjectValueName
  Path: Path
  CommandLine: 
    - Command
    - Process Command Line
  OldUacValue: OldUacValue
  SubStatus: SubStatus
  DisplayName: DisplayName
  TaskContent: TaskContent
  ServiceSid: ServiceSid
  CertThumbprint: CertThumbprint
  ClassName: ClassName
  NotificationPackageName: NotificationPackageName
  NewSd: NewSd
  TestSigning: TestSigning
  TargetInfo: TargetInfo
  ClientProcessId: ClientProcessId
  ParentProcessId: ParentProcessId
  AccessList: AccessList
  GroupMembership: 
    - GroupMembership
    - GroupName
  FilterName: FilterName
  ChangeType: ChangeType
  LayerName: LayerName
  ServiceAccount: ServiceAccount
  AttributeValue: AttributeValue
  SessionName: SessionName
  TaskName: 
    - TaskName
    - Task Name
  ObjectDN: ObjectDN
  TemplateContent: TemplateContent
  NewTemplateContent: NewTemplateContent
  SourcePort: sourceport
  PasswordLastSet: PasswordLastSet
  PrivilegeList: PrivilegeList
  DeviceDescription: DeviceDescription
  TargetServerName: TargetServerName
  NewTargetUserName: NewTargetUserName
  OperationType: OperationType
  DestPort: destinationport
  ServiceStartType: ServiceStartType
  OldTargetUserName: OldTargetUserName
  UserPrincipalName: UserPrincipalName
  Accesses: Accesses
  DnsHostName: DnsHostName
  DisableIntegrityChecks: DisableIntegrityChecks
  AuditSourceName: AuditSourceName
  Workstation: Machine Identifier
  DestAddress: destinationip
  PreAuthType: PreAuthType
  SecurityPackageName: SecurityPackageName
  SubjectLogonId: SubjectLogonId
  NewUacValue: NewUacValue
  EnabledPrivilegeList: EnabledPrivilegeList
  RelativeTargetName: RelativeTargetName
  CertSerialNumber: RelativeTargetName
  SidHistory: SidHistory
  TargetLogonId: TargetLogonId
  KernelDebug: KernelDebug
  CallerProcessName: CallerProcessName
  ProcessName: Process Name
  Properties: Properties
  UserAccountControl: UserAccountControl
  RegistryValue: Target Object
  SecurityID: SecurityID
  ServiceFileName: 
    - Service Filename
    - ServiceFileName
    - Service File Name
  SecurityDescriptor: SecurityDescriptor
  ServiceName: Service Name
  ShareName: 
    - Share Name
    - ShareName
  NewValue: NewValue
  Source: Source
  Status: Status
  SubjectAccountName: 
    - Subject Account Name
    - SubjectAccountName
  SubjectDomainName: SubjectDomainName
  SubjectUserName: Target Username
  SubjectUserSid: SubjectUserSid
  SourceAddr: sourceip
  SourceAddress: 
    - sourceip
    - sourceaddress
  TargetFilename: File Directory
  TargetName: Target Username
  ServicePrincipalNames: ServicePrincipalNames
  TargetDomainName: TargetDomainName
  TargetSid: TargetSid
  TargetUserName: 
    - Target Username
    - Target User Name
  ObjectServer: ObjectServer
  TargetUserSid: TargetUserSid
  TicketEncryptionType: TicketEncryptionType
  TicketOptions: TicketOptions
  WorkstationName: Machine Identifier
  TransmittedServices: TransmittedServices
  AuthenticationAlgorithm: AuthenticationAlgorithm
  LayerRTID: LayerRTID
  BSSID: BSSID
  BSSType: BSSType
  CipherAlgorithm: CipherAlgorithm
  ConnectionId: ConnectionId
  ConnectionMode: ConnectionMode
  InterfaceDescription: InterfaceDescription
  InterfaceGuid: InterfaceGuid
  OnexEnabled: OnexEnabled
  PHYType: PHYType
  ProfileName: ProfileName
  SSID: SSID
  Domain: Domain
  ServiceType: ServiceType
  SourceName: SourceName
  StartType: StartType
  UserID: UserID
  ParentProcessName: Parent Process Name
  Service: Service
  hasIdentity: hasIdentity