platform: Palo Alto XSIAM
source: windows_security

default_log_source:
  preset: xdr_event_log

field_mapping:
  EventID: action_evtlog_event_id
  Provider_Name: provider_name

raw_log_fields:
  ParentImage: regex
  AccessMask: regex
  AccountName: regex
  AllowedToDelegateTo: regex
  AttributeLDAPDisplayName: regex
  AuditPolicyChanges: regex
  AuthenticationPackageName: regex
  CallingProcessName: regex
  Channel: regex
  ComputerName: regex
  EventType: regex
  FailureReason: regex
  FileName: regex
  GrantedAccess: regex
  Hashes: regex
  HiveName: regex
  IpAddress: regex
  IpPort: regex
  KeyLength: regex
  LogonProcessName: regex
  LogonType: regex
  LinkName: regex
  ProcessId: regex
  PublishURLs: regex
  ElevatedToken: regex
  MemberName: regex
  MemberSid: regex
  NewProcessName: regex
  ObjectClass: regex
  ObjectName: regex
  ObjectType: regex
  ObjectValueName: regex
  Path: regex
  CommandLine: regex
  OldUacValue: regex
  CertIssuerName: regex
  SubStatus: regex
  DisplayName: regex
  TaskContent: regex
  ServiceSid: regex
  CertThumbprint: regex
  ClassName: regex
  NotificationPackageName: regex
  NewSd: regex
  TestSigning: regex
  TargetInfo: regex
  ParentProcessId: regex
  AccessList: regex
  GroupMembership: regex
  FilterName: regex
  ChangeType: regex
  LayerName: regex
  ServiceAccount: regex
  ClientProcessId: regex
  AttributeValue: regex
  SessionName: regex
  TaskName: regex
  ObjectDN: regex
  TemplateContent: regex
  NewTemplateContent: regex
  SourcePort: regex
  PasswordLastSet: regex
  PrivilegeList: regex
  DeviceDescription: regex
  TargetServerName: regex
  NewTargetUserName: regex
  OperationType: regex
  DestPort: regex
  ServiceStartType: regex
  OldTargetUserName: regex
  UserPrincipalName: regex
  Accesses: regex
  DnsHostName: regex
  DisableIntegrityChecks: regex
  AuditSourceName: regex
  Workstation: regex
  DestAddress: regex
  PreAuthType: regex
  SecurityPackageName: regex
  SubjectLogonId: regex
  NewUacValue: regex
  EnabledPrivilegeList: regex
  RelativeTargetName: regex
  CertSerialNumber: regex
  SidHistory: regex
  TargetLogonId: regex
  KernelDebug: regex
  CallerProcessName: regex
  ProcessName: regex
  Properties: regex
  UserAccountControl: regex
  RegistryValue: regex
  SecurityID: regex
  ServiceFileName: regex
  SecurityDescriptor: regex
  ServiceName: regex
  ShareName: regex
  NewValue: regex
  Source: regex
  Status: regex
  SubjectDomainName: regex
  SubjectUserName: regex
  SubjectUserSid: regex
  SourceAddr: regex
  SourceAddress: regex
  TargetName: regex
  ServicePrincipalNames: regex
  TargetDomainName: regex
  TargetSid: regex
  TargetUserName: regex
  ObjectServer: regex
  TargetUserSid: regex
  TicketEncryptionType: regex
  TicketOptions: regex
  WorkstationName: regex
  TransmittedServices: regex
  AuthenticationAlgorithm: regex
  LayerRTID: regex
  BSSID: regex
  BSSType: regex
  CipherAlgorithm: regex
  ConnectionId: regex
  ConnectionMode: regex
  InterfaceDescription: regex
  InterfaceGuid: regex
  OnexEnabled: regex
  PHYType: regex
  ProfileName: regex
  SSID: regex
  Domain: regex
  ServiceType: regex
  SourceName: regex
  StartType: regex
  UserID: regex
  ParentProcessName: regex
  ExceptionCode: regex
  Service: regex
  SamAccountName: regex
  ImpersonationLevel: regex
  PrimaryGroupId: regex