platform: Palo Alto XSIAM
source: windows_security

default_log_source:
  dataset: microsoft_windows_raw

field_mapping:
  EventID: action_evtlog_event_id
  Provider_Name: provider_name

raw_log_fields:
  - ParentImage
  - AccessMask
  - AccountName
  - AllowedToDelegateTo
  - AttributeLDAPDisplayName
  - AuditPolicyChanges
  - AuthenticationPackageName
  - CallingProcessName
  - Channel
  - ComputerName
  - EventType
  - FailureReason
  - FileName
  - GrantedAccess
  - Hashes
  - HiveName
  - IpAddress
  - IpPort
  - KeyLength
  - LogonProcessName
  - LogonType
  - LinkName
  - ProcessId
  - PublishURLs
  - ElevatedToken
  - MemberName
  - MemberSid
  - NewProcessName
  - ObjectClass
  - ObjectName
  - ObjectType
  - ObjectValueName
  - Path
  - CommandLine
  - OldUacValue
  - CertIssuerName
  - SubStatus
  - DisplayName
  - TaskContent
  - ServiceSid
  - CertThumbprint
  - ClassName
  - NotificationPackageName
  - NewSd
  - TestSigning
  - TargetInfo
  - ParentProcessId
  - AccessList
  - GroupMembership
  - FilterName
  - ChangeType
  - LayerName
  - ServiceAccount
  - ClientProcessId
  - AttributeValue
  - SessionName
  - TaskName
  - ObjectDN
  - TemplateContent
  - NewTemplateContent
  - SourcePort
  - PasswordLastSet
  - PrivilegeList
  - DeviceDescription
  - TargetServerName
  - NewTargetUserName
  - OperationType
  - DestPort
  - ServiceStartType
  - OldTargetUserName
  - UserPrincipalName
  - Accesses
  - DnsHostName
  - DisableIntegrityChecks
  - AuditSourceName
  - Workstation
  - DestAddress
  - PreAuthType
  - SecurityPackageName
  - SubjectLogonId
  - NewUacValue
  - EnabledPrivilegeList
  - RelativeTargetName
  - CertSerialNumber
  - SidHistory
  - TargetLogonId
  - KernelDebug
  - CallerProcessName
  - ProcessName
  - Properties
  - UserAccountControl
  - RegistryValue
  - SecurityID
  - ServiceFileName
  - SecurityDescriptor
  - ServiceName
  - ShareName
  - NewValue
  - Source
  - Status
  - SubjectDomainName
  - SubjectUserName
  - SubjectUserSid
  - SourceAddr
  - SourceAddress
  - TargetName
  - ServicePrincipalNames
  - TargetDomainName
  - TargetSid
  - TargetUserName
  - ObjectServer
  - TargetUserSid
  - TicketEncryptionType
  - TicketOptions
  - WorkstationName
  - TransmittedServices
  - AuthenticationAlgorithm
  - LayerRTID
  - BSSID
  - BSSType
  - CipherAlgorithm
  - ConnectionId
  - ConnectionMode
  - InterfaceDescription
  - InterfaceGuid
  - OnexEnabled
  - PHYType
  - ProfileName
  - SSID
  - Domain
  - ServiceType
  - SourceName
  - StartType
  - UserID
  - ParentProcessName
  - ExceptionCode
  - Service